version: '2'

services:      
  mongo:
        container_name: mongo
        image: mongo:latest
        ports:
            - 27017:27017
        environment:
            - MONGO_DATA_DIR=/data/db
            - MONGO_LOG_DIR=/dev/null
        volumes:
            - ./data/mongo:/data/db    

  mongoexpress:
          image: mongo-express
          depends_on:
              - "mongo"
          links:
              - "mongo"
          ports:
              - 8081:8081  
          environment: 
              ME_CONFIG_MONGODB_SERVER: mongo
              ME_CONFIG_OPTIONS_EDITORTHEME: ambiance
